### ISSUE TITLE
mPLUG-Owl have been updated.

### ISSUE THREAD

**Issue by MAGAer13** [OpenGVLab/Multi-Modality-Arena#1]
Hi, just quick note that mPLUG-Owl has been updated with two different checkpoint (lora & ft). Would you mind replacing the online arena demo? Thanks!

**Comment by MAGAer13** [comment]
Besides, I saw the leakage of "AI:" or "Assistant:" signal. Maybe try to use the following prompt and latest model to avoid it.
```python
prompt = '''The following is a conversation between a curious human and AI assistant. The assistant gives helpful, detailed, and polite answers to the user's questions.
Human: <image>
Human: {}
AI: '''.format(question)
```

Thanks again!

**Comment by wqshao126** [comment]
Thanks for your suggestion. We have updated arena according to it.
