### ISSUE TITLE
Could be possible to make Leaderboard page online with latest updates?

### ISSUE THREAD

**Issue by bymihaj** [OpenGVLab/Multi-Modality-Arena#3]

**Comment by wqshao126** [comment]
Hi, we have released the leaderboard of the multimodal chatbot arena. Feel free to explore it within the tab of the LVLM leaderboard at http://vlarena.opengvlab.com/. As part of our ongoing efforts, we will periodically update the LVLM Arena leaderboard.

**Comment by wqshao126** [comment]
> _No description provided._

**Comment by wqshao126** [comment]
> _No description provided._
