### ISSUE TITLE
Submit users' own evaluation results to the benchmark

### ISSUE THREAD

**Issue by Aopolin-Lv** [OpenGVLab/Multi-Modality-Arena#4]
Hello, authors. It is an amazing work. 
Do you consider about adding the function which support users submit their own evaluation results to the benchmark like [C-eval](https://cevalbenchmark.com/)?

**Comment by BellXP** [comment]
Thank you for your inquiry. The latest version of the code can be found in the LVLM_evaluation folder. This directory contains comprehensive evaluation code along with the necessary datasets. If you're interested in participating in the evaluation, please feel free to share your evaluation results or the model inference API with us via email at xupeng@pjlab.org.cn。
